version: '2.4'

services:
  src:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./src:/src
    depends_on:
      redis:
        condition: service_healthy
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'

  redis:
    image: redis
    healthcheck:
      test: redis-cli ping
